import szamitogep_program_metodusokkal

lista = szamitogep_program_metodusokkal.lista_megadasa()
szamitogep_program_metodusokkal.kiiras(lista)
szamitogep_program_metodusokkal.atlag(lista)
szamitogep_program_metodusokkal.legtobb(lista)
szamitogep_program_metodusokkal.megszamlalas(lista)
szamitogep_program_metodusokkal.eldontes(lista)
